#!/usr/bin/env python

share_dir = '.'
locale_dir = './po'

import locale
import gettext
from gtk import glade
from PacStats import app

locale.setlocale(locale.LC_ALL, '')
for module in gettext, glade:
	module.bindtextdomain('pacstats', locale_dir)
	module.textdomain('pacstats')
gettext.install('pacstats', locale_dir, unicode=1)

app = app.Application(share_dir)
app.run()
