#!/usr/bin/env python
## pacstats
##
## PacStats: Statistical charts about Archlinux pacman activity
## Copyright (C) 2010 Angelo "Encelo" Theodorou <encelo@gmail.com>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##


share_dir = '.'
locale_dir = './po'

import locale
import gettext
from gtk import glade
from PacStats import app

locale.setlocale(locale.LC_ALL, '')
for module in gettext, glade:
	module.bindtextdomain('pacstats', locale_dir)
	module.textdomain('pacstats')
gettext.install('pacstats', locale_dir, unicode=1)

app = app.Application(share_dir)
app.run()
