#!/usr/bin/env python

share_dir = '.'
locale_dir = './po'
charts_dir = '.'

import locale
import gettext
from PacStats import app
import gtk

locale.setlocale(locale.LC_ALL, '')
gtk.glade.bindtextdomain('pacstats', locale_dir)
gtk.glade.textdomain('pacstats')
gettext.install('pacstats', locale_dir, unicode=1)

app = app.Application(share_dir, charts_dir)
app.run()
